In [14]:
import numpy as np

a = np.random.randn(4, 3) 
b = np.random.randn(1, 3) 
c = a*b

print(a)
print(b)
#print(c)

[[ 1.2122002   1.72291829  0.56711236]
 [-1.01878693 -0.64042351 -0.29518216]
 [-0.33454796  0.12189416  0.30346625]
 [-1.58600321  0.31244188  1.54458704]]
[[ 0.58120716  1.73807469 -1.07510308]]


In [65]:
a = np.random.randn(4, 3) # a.shape = (12288, 150)
b = np.random.randn(3, 2) # b.shape = (150, 45)
c = np.dot(a,b)

print(a)
print('**')

print(b)
print('**')
print(c)

[[ 0.95478729  0.92399417 -0.15020376]
 [-0.17880685 -0.85720384 -0.92932371]
 [ 0.2484485  -0.26836454 -0.52648791]
 [ 1.26888898 -0.66629434 -0.17475593]]
**
[[ 1.14407838 -0.73040669]
 [-1.56550423 -0.9283744 ]
 [ 3.42228401 -0.02697466]]
**
[[-0.86820522 -1.55114386]
 [-2.0430225   0.95147601]
 [-1.09742078  0.08187615]
 [ 1.89673062 -0.30352041]]


In [66]:
-1.40833813 * 0.16215622

-0.22837078764266858

In [67]:
a = np.random.randn(3,4)
b = np.random.randn(4,1)
print('This is a')
print(a)

print('This is b')
print(b)

print('This is d')
d = a + b.T
print(d)

print(' - - - ')
for i in range(3):
    for j in range(4):
        c[i][j] = a[i][j] + b[j]

print(c)


This is a
[[ 0.28975778 -0.54175511 -0.37048228 -1.15881538]
 [-0.56375362 -0.88605244 -0.468096    0.93847122]
 [-0.71299096  1.48470891 -0.67528281 -0.65077366]]
This is b
[[-0.41593971]
 [-0.62836325]
 [ 1.43963442]
 [ 0.09061758]]
This is d
[[-0.12618193 -1.17011836  1.06915214 -1.06819779]
 [-0.97969333 -1.51441569  0.97153842  1.0290888 ]
 [-1.12893066  0.85634566  0.76435161 -0.56015608]]
 - - - 


IndexError: index 2 is out of bounds for axis 0 with size 2

In [68]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b
print('a')
print(a)
print('b')
print(b)
print('c'
     
     )
print(c)

a
[[-1.6906597  -0.28183416  0.02144009]
 [-1.2135198  -0.09933279 -0.06127147]
 [-0.16066175  0.70855713  0.16228649]]
b
[[ 0.23894359]
 [-1.19549277]
 [-2.21665123]]
c
[[-0.4039723  -0.06734247  0.00512297]
 [ 1.45075415  0.11875163  0.0732496 ]
 [ 0.35613107 -1.57062404 -0.35973256]]


In [72]:
adam = [3, 4,6]
bal = [8,7,2]


In [73]:
c= np.dot(adam,bal)

In [74]:
print(c)

64


In [81]:
say=2
ca=np.dot(adam, say)
print(ca)

[ 6  8 12]


In [85]:
sey=np.dot(adam, say)
print(sey)

[ 6  8 12]


In [88]:
subt= np.subtract(adam,bal)
print(subt)

[-5 -3  4]


In [89]:
5*subt

array([-25, -15,  20])

In [90]:
print(adam)

[3, 4, 6]


In [91]:
(1-adam)

TypeError: unsupported operand type(s) for -: 'int' and 'list'

In [147]:
print(adam)
print(bal)

[3, 4, 6]
[8, 7, 2]


In [161]:
bal = [4,6,4,3,2]


AttributeError: 'list' object has no attribute 'reshape'

In [94]:
ela=5
np.divide(1,ela)

0.20000000000000001

In [141]:
def sigmoid(z):
    """
    Compute the sigmoid of z

    Arguments:
    z -- A scalar or numpy array of any size.

    Return:
    s -- sigmoid(z)
    """

    ### START CODE HERE ### (≈ 1 line of code)
    s = 1 / (1 + np.exp(-z))
    ### END CODE HERE ###
    
    return s


w, b, X, Y = np.array([[1.],[2.]]), 2., np.array([[1.,2.,-1.],[3.,4.,-3.2]]), np.array([[1,0,1]])
m = X.shape[1]
A = sigmoid( np.dot(w.T,X) + b )    
A = np.reshape(A, m)
#np.sum( np.dot(Y,np.log(A)), np.dot(np.subtract(1,Y),np.log(np.subtract(1,A))) )
np.dot(np.subtract(1,Y),np.log(np.subtract(1,A)))

AA=np.dot(Y,np.log(A))
print(AA)

BB=np.dot(np.subtract(1,Y),np.log(np.subtract(1,A)))
print(BB)


[-5.40462981]
[-12.00000614]


In [144]:
AA+BB

array([-17.40463596])

In [146]:
Y_prediction = np.zeros((1,5))
print(Y_prediction)
Y_prediction += 1
print(Y_prediction)


[[ 0.  0.  0.  0.  0.]]
[[ 1.  1.  1.  1.  1.]]


In [1]:
+

SyntaxError: invalid syntax (<ipython-input-1-c30dba8197a1>, line 1)

In [2]:
!tar cvfz notebook.tar.gz *

Python Basics With Numpy v3.ipynb
images/
images/image2vector_kiank.png
images/image2vector.png
images/Sigmoid.png
my tests.ipynb


!tar -zxcf mynew.tar ~/Week 2/

In [3]:
!tar cvfz mynew.tar ~/Week 2/

tar: Removing leading `/' from member names
tar: /home/jovyan/Week: Cannot stat: No such file or directory
tar: 2: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors


In [14]:
import numpy as np
A = np.random.randn(4,3)
B = np.sum(A, axis = 1, keepdims = True)
print(A)
print(B)

[[-0.22398379  0.25409427 -0.80648749]
 [-1.57773784  2.12816602  1.39338238]
 [-1.19273507 -1.44447484 -0.49820701]
 [ 0.71290527 -0.62810543 -0.61494634]]
[[-0.77637701]
 [ 1.94381057]
 [-3.13541692]
 [-0.5301465 ]]


In [13]:
adam=[  -0.18768205 ,  -0.27286905  ,   0.97810766 , -0.57650409 ]
sum(adam)


-0.05894752999999997

In [15]:
print(adam)

[-0.18768205, -0.27286905, 0.97810766, -0.57650409]


In [22]:
apple = [[4, 6 , 7, 9], [ 1, 3, 5,2],[6, 9, 2 ,4]]

In [27]:
print(apple)

[[4, 6, 7, 9], [1, 3, 5, 2], [6, 9, 2, 4]]


In [ ]:
pie = [[1,2,4,6],[2,4,6]]